#
# Module manifest for module 'MSc365.Idp.Toolbox'
#
# Generated by: Martin Swinkels
#
# Generated on: 25/09/2025
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule           = 'MSc365.Idp.Toolbox.psm1'

    # Version number of this module.
    ModuleVersion        = '0.1.0'

    # Supported PSEditions - Specify for better compatibility
    CompatiblePSEditions = 'Core'

    # ID used to uniquely identify this module
    GUID                 = '725b7a9f-7858-43b1-876f-6db9fbc0f01e'

    # Author of this module
    Author               = 'Martin Swinkels'

    # Company or vendor of this module
    CompanyName          = 'MSc365.eu, Portugal'

    # Copyright statement for this module
    Copyright            = '(c) MSc365.eu. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'An experimental PowerShell module providing a comprehensive set of tools for Internal Developer Platforms (IDPs) on Azure cloud.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '7.4'

    # Minimum version of Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Functions to export from this module - Be explicit for security
    FunctionsToExport    = @(
        'New-RandomPassword'
    )

    # Cmdlets to export from this module - Use empty array if none
    CmdletsToExport      = @()

    # Variables to export from this module - Use empty array if none
    VariablesToExport    = @()

    # Aliases to export from this module - Use empty array if none
    AliasesToExport      = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData          = @{
        PSData = @{
            # Tags applied to this module for PowerShell Gallery discovery
            Tags                     = @('Azure', 'IDP', 'Toolbox', 'Utilities', 'Security', 'Password', 'DevOps', 'Platform')

            # A URL to the license for this module
            LicenseUri               = 'https://github.com/msc365/az-idp-toolbox/blob/main/LICENSE'

            # A URL to the main website for this project
            ProjectUri               = 'https://github.com/msc365/az-idp-toolbox'

            # A URL to an icon representing this module
            IconUri                  = 'https://raw.githubusercontent.com/msc365/az-idp-toolbox/main/.assets/icon.png'

            # ReleaseNotes of this module
            ReleaseNotes             = 'https://github.com/msc365/az-idp-toolbox/blob/main/CHANGELOG.md'

            # Prerelease string of this module
            # Prerelease = 'beta1'

            # Flag to indicate whether the module requires explicit user acceptance
            RequireLicenseAcceptance = $false
        }
    }

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ""
}
