---
name: "Bug report \U0001F41B"
about: Report errors or unexpected behavior
title: "Bug: "
labels: ['needs triage :wave:', 'bug :beetle:']
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
