---
name: "Feature request \U0001F680"
description: "Suggest an idea for this project"
title: "[Request] " 
labels: ['needs triage :wave:', 'enhancement :sparkles:']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a feature request.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the proposed feature.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    attributes:
      label: Related function
      description: Which function is related to your request?
      multiple: false
      options:
        - New-RandomPassword
        - Other
        - Not relevant
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Infra as Code type
      description: Are you using Bicep or Terraform?
      multiple: false
      options:
        - Bicep
        - Terraform
        - Both
        - Not relevant
    validations:
      required: false
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Describe the use case for this feature
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe how this feature could be implemented
    validations:
      required: true
